title:            Takku's DevFolio
description:      Welcome to my site.
# Your site's domain goes here. Leave localhost server or blank when working locally.
url:              https://takkujunjieli.github.io
disqus_shortname: takkujl

# Owner/author information
owner:
  name:           Junjie (Takku) Li 
  avatar:         avatar.svg
  bio:            I grew up from Quzhou, Zhejiang, China. Currently in Bothell, WA, USA. Passionate about deep learning in general, and content creation, while exploring the world.
  email:          alvinbluy@gmail.edu
  # Social networking links are used in author-bio sidebar. Update and remove as you like.
  linkedin: junjietakkuli
  github: takkujunjieli
# Analytics and webmaster tools stuff goes here
# google_analytics: UA-52736040-1
# google_verify:
# # https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
# bing_verify:

# Links to include in top navigation
# For external links add external: true
links:
  - title: Projects
    url: /projects/
  - title: Experiences
    url: /experiences/
  - title: Blogs
    url: /blogs/
  - title: Personal
    url: /personal/

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    US/Pacific
future:      true
#pygments:    true
highlighter: rouge
markdown:    kramdown
kramdown:
  extensions: ["strikethrough"]

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title/

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

  coderay:
    coderay_line_numbers:
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "vendor", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
